{% set name = "Metafone" %}
{% set version = "0.5" %}
{% set hashtype = "md5" %}
{% set hash = "de53b4c513a985cca9b7a48181152b9b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: Metafone-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hashtype }}: {{ hash }}

build:
  noarch: python
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools
        - future
    run:
        - python
        - future

test:
    imports:
        - metaphone

about:
    home: https://github.com/oubiwann/metaphone
    license: BSD 3-clause
    license_family: BSD
    summary: A Python implementation of the double metaphone algorithms

extra:
    recipe-maintainers:
        - wyseguy7
        - ericdill
