{% set version = "0.5" %}

package:
  name: metafone
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/M/Metafone/Metafone-{{ version }}.tar.gz
  sha256: db34f0c1cedc1086493a5beec9a1a702325fd2b1d314515bd50f0a23131b0240

build:
  number: 1001
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
    - future
  run:
    - python
    - future

test:
  imports:
    - metaphone

about:
  home: https://github.com/oubiwann/metaphone
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'A Python implementation of the double metaphone algorithms'

extra:
  recipe-maintainers:
    - wyseguy7
