travis:
  secure:
    BINSTAR_TOKEN: U9KZE/w8Wuzta1RnQ1v6qVgyXCOF7PTY5TT7JwcamQ3cAOzI4+PsLv7thqffF/JaqLq0lL7+QcmOK8MtuRRb+eFsRHCFtIu/VY3E3n+8ZqyXFAJJWlK/gaLoIZBK3EmAB9VFrw/40zMcYE9S5q+8a+r8nBv+W9JxVMduEz2JKUMMOnTQ3dyvnQstMRipGladn4ss1BOc2oUoR38s8RDiK8i2LBhR0CvFMOVgvso8e/F/Plt3Kvb0w2EUqKCPKdfOAw54CF3qmVPUaelhADbMaLydDiiivrohuX/MhGb0B0pXD0AFOnt+XPMKyTa/UjhJ0W/Cmo4RtNRzsGIejcKN9uTfD0Wu8g4KQ+PaqetfdK82+2eB9t9zZxiKVjK/7LLz9e3dZcBu9mhmPKHT4JPb/hDxh7fMk8Ghm/rNLQ0zrGjXiMrnqjfDgQ8A/hFWSULBL1jJOTH+2OjI/ixrL6h84OO5cUSvhL/WnGImLmAuUtyWKDFYySRImxNY/N/OziHBD2slvMPBJGlcUcHvmGisDCO/x1JhSjwuNCBOzYpa4y12DAasjSBn15lcb/iE7/4tyiJjJrcDNhSx/Hos9PlSSwvyLZZydOCsWboR60ZW7Qh6eX/OrZkwVyokADznwkonVgEEQpEK5LWz9iSVElU+uGVBngbdEu/XCz7DWtDPxBU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
