appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jKwbNfC1quGmVz8MA/47Uw0dhoy6zrdAzat4LyCxOW3p9Obkudu1WLbf2B9awqjyIvTRx/Q43w+Rrq8j++hPD8bBO5CHNeIuK5ipjDDwAFbdyc5vIuMlsKZC1SpCz2sZquLF8Q7XNPqQtiXrHc9yxBjShie92psFOCft5nwTKf4E4EVA8IdXlPfvHzSLIK4Vj/rIiBwM9gsNoruNmDrGTfQenYmLwnJAUKQuT8OtImoIfcJYFKK0PVPYbX45AEcXAhVx7UyujJfIXQkF51JCST21qNyPRLkVhh8QIXUn4AOkOxyvgMe5YzaiFIlqL/9/Oc8//UyXUFq42H/NXdJdAF8rna/Qpc+f+ZmmURlqkQXq8abvSo26HvGBGGGi93JBvndUkB8SHDK3hwDjq94O017AsZEGudr16fPkrvE0VAUSxcNjc3BlNVbocZ1bOOwwOa8zgVi+p0vVJO69ScR2RkLEBfJ9ZYHHYwscdZmEdpl2wl6e+CMvfQIXIDWA+foekQf7lvbagC5C7RZqNEh42XU3H+vA0em0fBK/YQTisPqFETn8G3STlItmEqVedOQC/Puf6K/tPY70995E7hdYZY3nYp71SJ/cJjmwUPGRODjUC+x6SDKvXdDEARmeUicxVBs7p121nznxY3s8IKi1BeoimHGa4Fu/osPK111xH1M=}
conda_forge_output_validation: true
